// Build a portrait A4 PDF report of events in a date range. Same look as
// the Faculty Performance PDF.

import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

interface EventRow {
  id: string;
  title: string;
  venue: string;
  description: string;
  startAt: string;
  endAt: string | null;
  status: 'SCHEDULED' | 'CANCELLED';
  isPast: boolean;
  creatorName: string;
  creatorEmail: string;
  creatorRole: string;
  hasImage: boolean;
  hasVideo: boolean;
  registrationUrl: string;
  hasRegistration: boolean;
  reportUploaded: boolean;
  reportName: string;
  reportUploadedAt: string | null;
}

interface EventReportPayload {
  meta: {
    start: string | null;
    end: string | null;
    generatedAt: string;
    generatedBy: string;
    totalEvents: number;
    byStatus: Record<string, number>;
    byCreatorRole: Record<string, number>;
    pastCount: number;
    upcomingCount: number;
    reportsUploaded: number;
  };
  events: EventRow[];
}

const fmtDate = (s: string | null) =>
  s ? new Date(s).toLocaleDateString(undefined, { year: 'numeric', month: 'short', day: 'numeric' }) : '—';
const fmtTime = (s: string | null) =>
  s ? new Date(s).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) : '';

export function generateEventReportPDF(payload: EventReportPayload, rangeLabel: string) {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'pt', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 36;

  // === COVER ===
  doc.setFillColor(30, 41, 59);
  doc.rect(0, 0, pageW, 180, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(24);
  doc.text('Event Calendar Report', margin, 70);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(12);
  doc.text('GESoM — Graphic Era School of Management', margin, 92);
  doc.setFontSize(11);
  doc.text(`Period: ${rangeLabel}`, margin, 130);
  doc.text(`Generated: ${new Date(payload.meta.generatedAt).toLocaleString()}`, margin, 148);
  doc.text(`Generated by: ${payload.meta.generatedBy}`, margin, 166);

  // Stat cards row
  doc.setTextColor(15, 23, 42);
  const cards = [
    { label: 'Total events', value: payload.meta.totalEvents, color: [30, 41, 59] as [number, number, number] },
    { label: 'Scheduled', value: payload.meta.byStatus.SCHEDULED || 0, color: [22, 163, 74] as [number, number, number] },
    { label: 'Cancelled', value: payload.meta.byStatus.CANCELLED || 0, color: [220, 38, 38] as [number, number, number] },
    { label: 'Reports uploaded', value: payload.meta.reportsUploaded, color: [202, 138, 4] as [number, number, number] },
  ];
  let y = 220;
  const gap = 8;
  const cardW = (pageW - margin * 2 - gap * (cards.length - 1)) / cards.length;
  cards.forEach((c, i) => {
    const x = margin + i * (cardW + gap);
    doc.setFillColor(241, 245, 249);
    doc.roundedRect(x, y, cardW, 70, 6, 6, 'F');
    doc.setTextColor(...c.color);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(22);
    doc.text(String(c.value), x + cardW / 2, y + 36, { align: 'center' });
    doc.setTextColor(100, 116, 139);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.text(c.label, x + cardW / 2, y + 56, { align: 'center' });
  });

  // By creator role table
  y += 90;
  const roleRows = Object.entries(payload.meta.byCreatorRole).sort((a, b) => b[1] - a[1]);
  if (roleRows.length) {
    doc.setTextColor(15, 23, 42);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(13);
    doc.text('By creator role', margin, y);
    y += 8;
    autoTable(doc, {
      startY: y,
      head: [['Role', 'Events']],
      body: roleRows.map(([role, count]) => [role, String(count)]),
      styles: { fontSize: 9, cellPadding: 5 },
      headStyles: { fillColor: [30, 41, 59], textColor: 255, fontStyle: 'bold' },
      alternateRowStyles: { fillColor: [248, 250, 252] },
      columnStyles: { 1: { halign: 'right', fontStyle: 'bold' } },
      margin: { left: margin, right: margin },
    });
  }

  // === EVENTS TABLE PAGE(S) ===
  if (payload.events.length === 0) {
    doc.setTextColor(100, 116, 139);
    doc.setFontSize(11);
    doc.text('No events in this date range.', margin, ((doc as unknown as { lastAutoTable?: { finalY?: number } }).lastAutoTable?.finalY || y) + 30);
  } else {
    doc.addPage();
    doc.setTextColor(15, 23, 42);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.text(`All events (${payload.events.length})`, margin, 50);
    autoTable(doc, {
      startY: 64,
      head: [['Date', 'Time', 'Title', 'Venue', 'Creator', 'Status', 'Reg', 'Media', 'Report']],
      body: payload.events.map((e) => [
        fmtDate(e.startAt),
        `${fmtTime(e.startAt)}${e.endAt ? `–${fmtTime(e.endAt)}` : ''}`,
        e.title,
        e.venue || '—',
        e.creatorName + (e.creatorRole ? ` (${e.creatorRole})` : ''),
        e.status,
        e.hasRegistration ? 'Yes' : '—',
        [e.hasImage ? 'IMG' : '', e.hasVideo ? 'VID' : ''].filter(Boolean).join('/') || '—',
        e.reportUploaded ? 'Yes' : '—',
      ]),
      styles: { fontSize: 8, cellPadding: 4, overflow: 'linebreak' },
      headStyles: { fillColor: [30, 41, 59], textColor: 255, fontStyle: 'bold' },
      alternateRowStyles: { fillColor: [248, 250, 252] },
      margin: { left: margin, right: margin },
      columnStyles: {
        0: { cellWidth: 56, halign: 'center' },
        1: { cellWidth: 56, halign: 'center' },
        2: { cellWidth: 'auto' },
        3: { cellWidth: 70 },
        4: { cellWidth: 90 },
        5: { cellWidth: 46, halign: 'center' },
        6: { cellWidth: 28, halign: 'center' },
        7: { cellWidth: 36, halign: 'center' },
        8: { cellWidth: 36, halign: 'center' },
      },
      didParseCell: (data) => {
        if (data.section === 'body' && data.column.index === 5) {
          const txt = data.cell.text[0];
          if (txt === 'CANCELLED') data.cell.styles.textColor = [220, 38, 38];
          else if (txt === 'SCHEDULED') data.cell.styles.textColor = [22, 163, 74];
          data.cell.styles.fontStyle = 'bold';
        }
        if (data.section === 'body' && data.column.index === 8 && data.cell.text[0] === 'Yes') {
          data.cell.styles.textColor = [202, 138, 4];
          data.cell.styles.fontStyle = 'bold';
        }
      },
    });

    // === Per-event detail entries (compact) ===
    // For events that have a description or registration URL or report name,
    // emit a small detail block. Skip events with nothing to add.
    const detailEvents = payload.events.filter(
      (e) => e.description || e.registrationUrl || e.reportName,
    );
    if (detailEvents.length) {
      doc.addPage();
      doc.setFontSize(14);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(15, 23, 42);
      doc.text('Event details', margin, 50);
      let yy = 70;
      for (const e of detailEvents) {
        // page break if too low
        if (yy > pageH - 110) {
          doc.addPage();
          yy = 50;
        }
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(11);
        doc.setTextColor(15, 23, 42);
        doc.text(e.title, margin, yy);
        yy += 14;
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(9);
        doc.setTextColor(100, 116, 139);
        doc.text(
          `${fmtDate(e.startAt)} ${fmtTime(e.startAt)}${e.endAt ? ` – ${fmtTime(e.endAt)}` : ''}` +
          `${e.venue ? `   ·   ${e.venue}` : ''}   ·   by ${e.creatorName}${e.creatorRole ? ` (${e.creatorRole})` : ''}`,
          margin, yy,
        );
        yy += 12;
        if (e.description) {
          doc.setTextColor(60, 60, 60);
          const lines = doc.splitTextToSize(e.description, pageW - margin * 2);
          doc.text(lines, margin, yy);
          yy += lines.length * 10 + 4;
        }
        if (e.registrationUrl) {
          doc.setTextColor(37, 99, 235);
          doc.text(`Registration: ${e.registrationUrl}`, margin, yy);
          yy += 12;
        }
        if (e.reportName) {
          doc.setTextColor(202, 138, 4);
          doc.text(`Report: ${e.reportName}${e.reportUploadedAt ? ` (uploaded ${fmtDate(e.reportUploadedAt)})` : ''}`, margin, yy);
          yy += 12;
        }
        // divider
        doc.setDrawColor(226, 232, 240);
        doc.line(margin, yy, pageW - margin, yy);
        yy += 14;
      }
    }
  }

  // Footer
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i += 1) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(100, 116, 139);
    doc.setFont('helvetica', 'normal');
    doc.text(`Page ${i} of ${totalPages}`, pageW / 2, pageH - 18, { align: 'center' });
    doc.text('GESoM — Event Calendar Report', margin, pageH - 18);
  }

  const fname = `events-${rangeLabel.replace(/[^a-z0-9-]+/gi, '-').toLowerCase()}-${new Date().toISOString().slice(0, 10)}.pdf`;
  doc.save(fname);
}
