// Build a polished portrait PDF performance report.
// Uses jsPDF + jspdf-autotable (already deps via /admin/reports).

import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

type Priority = 'LOW' | 'MEDIUM' | 'HIGH' | 'URGENT';

interface TaskRow {
  title: string;
  priority: Priority;
  type: string;
  status: string;
  assignedAt: string;
  deadline: string;
  completedAt: string;
  late: string;
  documentName?: string;
  adminRemark?: string;
}

interface FacultyEntry {
  user: { id: string; firstName: string; lastName: string | null; email: string; approvedRole: string; department?: string };
  fullName: string;
  taskCount: number;
  tasks: TaskRow[];
  score: number;
  scoreBreakdown: {
    onTime: number; late1: number; late7: number; lateMore: number;
    overdue: number; notDueYet: number;
  };
}

interface PerformancePayload {
  meta: {
    start: string | null;
    end: string | null;
    facultyId: string | null;
    generatedAt: string;
    generatedBy: string;
    totalTasks: number;
    totalFaculty: number;
  };
  faculty: FacultyEntry[];
}

const fmtDate = (s: string | null) => (s ? new Date(s).toLocaleDateString(undefined, { year: 'numeric', month: 'short', day: 'numeric' }) : '—');

function scoreColor(score: number): [number, number, number] {
  if (score >= 100) return [22, 163, 74];   // green-600
  if (score >= 80) return [21, 128, 61];    // green-700
  if (score >= 60) return [202, 138, 4];    // yellow-600
  return [220, 38, 38];                     // red-600
}

export function generatePerformanceReportPDF(payload: PerformancePayload, rangeLabel: string) {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'pt', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 36;

  // === COVER PAGE ===
  doc.setFillColor(30, 41, 59); // slate-800
  doc.rect(0, 0, pageW, 180, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(24);
  doc.text('Faculty Performance Report', margin, 70);

  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text('DOMS — Department of Management Studies', margin, 92);

  doc.setFontSize(11);
  doc.text(`Period: ${rangeLabel}`, margin, 130);
  doc.text(`Generated: ${new Date(payload.meta.generatedAt).toLocaleString()}`, margin, 148);
  doc.text(`Generated by: ${payload.meta.generatedBy}`, margin, 166);

  // Summary cards
  doc.setTextColor(15, 23, 42);
  doc.setFontSize(11);
  let y = 220;

  doc.setFillColor(241, 245, 249); // slate-100
  doc.roundedRect(margin, y, (pageW - margin * 2 - 16) / 3, 80, 6, 6, 'F');
  doc.roundedRect(margin + (pageW - margin * 2 - 16) / 3 + 8, y, (pageW - margin * 2 - 16) / 3, 80, 6, 6, 'F');
  doc.roundedRect(margin + 2 * ((pageW - margin * 2 - 16) / 3 + 8), y, (pageW - margin * 2 - 16) / 3, 80, 6, 6, 'F');

  const cardW = (pageW - margin * 2 - 16) / 3;
  doc.setFontSize(28); doc.setFont('helvetica', 'bold');
  doc.text(String(payload.meta.totalFaculty), margin + cardW / 2, y + 42, { align: 'center' });
  doc.text(String(payload.meta.totalTasks), margin + cardW + 8 + cardW / 2, y + 42, { align: 'center' });
  const avgScore = payload.faculty.length
    ? Math.round(payload.faculty.reduce((s, f) => s + f.score, 0) / payload.faculty.length)
    : 0;
  doc.setTextColor(...scoreColor(avgScore));
  doc.text(`${avgScore}%`, margin + 2 * (cardW + 8) + cardW / 2, y + 42, { align: 'center' });
  doc.setTextColor(15, 23, 42);

  doc.setFontSize(9); doc.setFont('helvetica', 'normal');
  doc.text('Faculty included', margin + cardW / 2, y + 64, { align: 'center' });
  doc.text('Tasks in range', margin + cardW + 8 + cardW / 2, y + 64, { align: 'center' });
  doc.text('Average accuracy', margin + 2 * (cardW + 8) + cardW / 2, y + 64, { align: 'center' });

  // Leaderboard table
  y += 110;
  doc.setFontSize(13); doc.setFont('helvetica', 'bold');
  doc.text('Leaderboard', margin, y);
  y += 8;

  autoTable(doc, {
    startY: y,
    head: [['Rank', 'Faculty', 'Role', 'Department', 'Tasks (in range)', 'Score']],
    body: payload.faculty.map((f, i) => [
      String(i + 1),
      f.fullName,
      f.user.approvedRole,
      f.user.department || '—',
      String(f.taskCount),
      `${f.score}%`,
    ]),
    styles: { fontSize: 9, cellPadding: 5 },
    headStyles: { fillColor: [30, 41, 59], textColor: 255, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    columnStyles: {
      0: { halign: 'center', cellWidth: 36 },
      4: { halign: 'center' },
      5: { halign: 'right', fontStyle: 'bold' },
    },
    didParseCell: (data) => {
      if (data.section === 'body' && data.column.index === 5) {
        const f = payload.faculty[data.row.index];
        const [r, g, b] = scoreColor(f.score);
        data.cell.styles.textColor = [r, g, b];
      }
    },
    margin: { left: margin, right: margin },
  });

  // === PER-FACULTY DETAIL PAGES ===
  for (const f of payload.faculty) {
    doc.addPage();

    // Header band
    doc.setFillColor(30, 41, 59);
    doc.rect(0, 0, pageW, 80, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(18); doc.setFont('helvetica', 'bold');
    doc.text(f.fullName, margin, 36);
    doc.setFontSize(10); doc.setFont('helvetica', 'normal');
    doc.text(
      `${f.user.approvedRole}${f.user.department ? ' · ' + f.user.department : ''} · ${f.user.email}`,
      margin, 56,
    );

    // Score block (right-aligned)
    const [sr, sg, sb] = scoreColor(f.score);
    doc.setFillColor(255, 255, 255);
    doc.roundedRect(pageW - margin - 110, 18, 100, 48, 6, 6, 'F');
    doc.setFontSize(8); doc.setTextColor(100, 116, 139); doc.setFont('helvetica', 'bold');
    doc.text('ACCURACY', pageW - margin - 60, 32, { align: 'center' });
    doc.setFontSize(22); doc.setTextColor(sr, sg, sb);
    doc.text(`${f.score}%`, pageW - margin - 60, 56, { align: 'center' });

    let yy = 110;
    doc.setTextColor(15, 23, 42);
    doc.setFontSize(11); doc.setFont('helvetica', 'bold');
    doc.text('Performance breakdown (all live tasks)', margin, yy);
    yy += 10;

    // Breakdown table
    autoTable(doc, {
      startY: yy,
      head: [['On time (+5)', '≤1d late (+1)', '≤7d late (−1)', '>7d late (−3)', 'Overdue (−5)', 'Upcoming']],
      body: [[
        String(f.scoreBreakdown.onTime),
        String(f.scoreBreakdown.late1),
        String(f.scoreBreakdown.late7),
        String(f.scoreBreakdown.lateMore),
        String(f.scoreBreakdown.overdue),
        String(f.scoreBreakdown.notDueYet),
      ]],
      styles: { fontSize: 9, halign: 'center', cellPadding: 5 },
      headStyles: { fillColor: [241, 245, 249], textColor: 15, fontStyle: 'bold' },
      margin: { left: margin, right: margin },
      theme: 'grid',
    });

    type LastTable = { lastAutoTable?: { finalY?: number } };
    yy = ((doc as unknown as LastTable).lastAutoTable?.finalY || yy) + 20;

    doc.setFontSize(11); doc.setFont('helvetica', 'bold');
    doc.text(`Tasks in selected period (${f.taskCount})`, margin, yy);
    yy += 8;

    if (f.tasks.length === 0) {
      doc.setFontSize(10); doc.setFont('helvetica', 'italic');
      doc.setTextColor(107, 114, 128);
      doc.text('— No tasks in this period.', margin, yy + 12);
    } else {
      autoTable(doc, {
        startY: yy,
        head: [['Title', 'Priority', 'Status', 'Late?', 'Assigned', 'Deadline', 'Completed']],
        body: f.tasks.map((t) => [
          t.title,
          t.priority,
          t.status,
          t.late || '—',
          fmtDate(t.assignedAt),
          fmtDate(t.deadline),
          fmtDate(t.completedAt),
        ]),
        styles: { fontSize: 8, cellPadding: 4, overflow: 'linebreak' },
        headStyles: { fillColor: [30, 41, 59], textColor: 255, fontStyle: 'bold' },
        alternateRowStyles: { fillColor: [248, 250, 252] },
        margin: { left: margin, right: margin },
        columnStyles: {
          0: { cellWidth: 'auto' },
          1: { cellWidth: 50, halign: 'center' },
          2: { cellWidth: 60, halign: 'center' },
          3: { cellWidth: 40, halign: 'center' },
          4: { cellWidth: 65, halign: 'center' },
          5: { cellWidth: 65, halign: 'center' },
          6: { cellWidth: 65, halign: 'center' },
        },
        didParseCell: (data) => {
          if (data.section === 'body' && data.column.index === 3 && data.cell.text[0] === 'YES') {
            data.cell.styles.textColor = [194, 65, 12];
            data.cell.styles.fontStyle = 'bold';
          }
          if (data.section === 'body' && data.column.index === 2) {
            const txt = data.cell.text[0];
            if (txt === 'COMPLETED') data.cell.styles.textColor = [22, 163, 74];
            else if (txt === 'OVERDUE') data.cell.styles.textColor = [220, 38, 38];
          }
        },
      });
    }
  }

  // Footer with page numbers
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i += 1) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(100, 116, 139);
    doc.setFont('helvetica', 'normal');
    doc.text(`Page ${i} of ${totalPages}`, pageW / 2, pageH - 18, { align: 'center' });
    doc.text('DOMS — Faculty Performance Report', margin, pageH - 18);
  }

  // Save
  const fname = `faculty-performance-${rangeLabel.replace(/[^a-z0-9-]+/gi, '-').toLowerCase()}-${new Date().toISOString().slice(0, 10)}.pdf`;
  doc.save(fname);
}
