// Client-side report exporters: turn a JSON report payload from
// /api/reports/* into either an .xlsx or a .pdf and trigger a download.
//
// Backend returns:
//   { meta: { reportType, title, session, generatedAt, generatedBy, rowCount },
//     columns: [{key, label}, ...],
//     rows: [{...}, ...] }

import * as XLSX from 'xlsx';
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

export type ReportColumn = { key: string; label: string };
export type ReportRow = Record<string, unknown>;
export type ReportMeta = {
  reportType: string;
  title: string;
  session: { id: string; name: string } | null;
  generatedAt: string;
  generatedBy: string;
  rowCount: number;
};

export type ReportPayload = {
  meta: ReportMeta;
  columns: ReportColumn[];
  rows: ReportRow[];
};

const safeFilename = (s: string) =>
  s.toLowerCase().replace(/[^a-z0-9-_]+/g, '-').replace(/^-|-$/g, '') || 'report';

function buildFilename(meta: ReportMeta, ext: 'xlsx' | 'pdf') {
  const date = new Date().toISOString().slice(0, 10);
  const session = meta.session ? `-${safeFilename(meta.session.name)}` : '';
  return `${safeFilename(meta.reportType)}${session}-${date}.${ext}`;
}

function cellToString(value: unknown): string {
  if (value == null) return '';
  if (value instanceof Date) return value.toISOString();
  if (typeof value === 'object') return JSON.stringify(value);
  return String(value);
}

export function exportToExcel(report: ReportPayload) {
  const { meta, columns, rows } = report;

  // First sheet: header info
  const headerRows: (string | number)[][] = [
    [meta.title],
    [`Session: ${meta.session?.name || '(not session-scoped)'}`],
    [`Generated by: ${meta.generatedBy}`],
    [`Generated at: ${meta.generatedAt}`],
    [`Rows: ${meta.rowCount}`],
    [],
  ];

  // Column header
  headerRows.push(columns.map((c) => c.label));

  // Data rows
  for (const r of rows) {
    headerRows.push(columns.map((c) => {
      const v = (r as Record<string, unknown>)[c.key];
      // Numbers stay numbers; everything else as string
      if (typeof v === 'number') return v;
      return cellToString(v);
    }));
  }

  const ws = XLSX.utils.aoa_to_sheet(headerRows);

  // Column widths — rough autosize
  const colWidths = columns.map((c) => {
    let max = c.label.length;
    for (const r of rows) {
      const v = cellToString((r as Record<string, unknown>)[c.key]);
      if (v.length > max) max = v.length;
    }
    return { wch: Math.min(60, Math.max(10, max + 2)) };
  });
  (ws as XLSX.WorkSheet)['!cols'] = colWidths;

  // Merge the title cell across all columns for visual heading
  if (columns.length > 1) {
    (ws as XLSX.WorkSheet)['!merges'] = [
      { s: { r: 0, c: 0 }, e: { r: 0, c: columns.length - 1 } },
    ];
  }

  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, meta.title.slice(0, 31));
  XLSX.writeFile(wb, buildFilename(meta, 'xlsx'));
}

export function exportToPDF(report: ReportPayload) {
  const { meta, columns, rows } = report;

  // Landscape if many columns; portrait otherwise
  const orientation = columns.length > 5 ? 'landscape' : 'portrait';
  const doc = new jsPDF({ orientation, unit: 'pt', format: 'a4' });

  const pageWidth = doc.internal.pageSize.getWidth();
  let cursorY = 40;

  // Title
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.text(meta.title, pageWidth / 2, cursorY, { align: 'center' });
  cursorY += 20;

  // Sub-header
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(80);
  if (meta.session) {
    doc.text(`Session: ${meta.session.name}`, 40, cursorY);
    cursorY += 12;
  }
  doc.text(`Generated by: ${meta.generatedBy}`, 40, cursorY);
  cursorY += 12;
  doc.text(`Generated at: ${meta.generatedAt}`, 40, cursorY);
  cursorY += 12;
  doc.text(`Rows: ${meta.rowCount}`, 40, cursorY);
  cursorY += 16;
  doc.setTextColor(0);

  // Table
  autoTable(doc, {
    startY: cursorY,
    head: [columns.map((c) => c.label)],
    body: rows.map((r) =>
      columns.map((c) => cellToString((r as Record<string, unknown>)[c.key])),
    ),
    styles: {
      fontSize: 7,
      cellPadding: 3,
      overflow: 'linebreak',
      valign: 'top',
    },
    headStyles: {
      fillColor: [30, 58, 138], // navy
      textColor: 255,
      fontStyle: 'bold',
    },
    alternateRowStyles: { fillColor: [243, 244, 246] },
    margin: { left: 20, right: 20 },
    didDrawPage: (data) => {
      const pageNumber = doc.getNumberOfPages();
      const pageSize = doc.internal.pageSize;
      doc.setFontSize(8);
      doc.setTextColor(120);
      doc.text(
        `Page ${pageNumber}`,
        pageSize.getWidth() - 40,
        pageSize.getHeight() - 12,
        { align: 'right' },
      );
      doc.setTextColor(0);
    },
  });

  doc.save(buildFilename(meta, 'pdf'));
}
